### PR TITLE
add flask env variable

### PR DESCRIPTION
**Pull request by vincentDcmps**

### CODE REVIEW

**Comment by ogarcia** [comment]
I'm sorry, but this doesn't make any sense. As say README, the *standalone* mode is designed to run a debug server on port 5000 so `FLASK_ENV` variable should **always** be development.

In the other hand, an environment variable does not have to be specifically declared in the dockerfile for you to use it, so you can perfectly well start the container by passing the value of `FLASK_ENV` to start it in another mode than *standalone*. For example:
```sh
docker run -d \
  --name=supysonic \
  -v /my/supysonic/data:/var/lib/supysonic \
  -v /my/supysonic/logs:/var/log/supysonic \
  -v /my/media/directory:/media \
  -e FLASK_APP="supysonic.web:create_application()" \
  -e FLASK_ENV="production" \
  -p 5000:5000 \
  --entrypoint="flask" \
  ogarcia/supysonic -- run -h 0.0.0.0
```

**Comment by vincentDcmps** [comment]
ok thanks for information.
I use standalone mode without debug because I'm on a nomad cluster and I don't think that we can use FCGI with socket in this case .
with your example we can't launch daemon in same container than server

**Comment by vincentDcmps** [comment]
you are OK if I propose gunicorn support with according commit https://github.com/vincentDcmps/docker-supysonic/commit/9182fac3ba607abcac3b89c3060a2520436f449b

**Comment by ogarcia** [comment]
I just added a new option to run with fcgi listen in a port. Simply run:
```
docker run -d \
  --name=supysonic \
  -e SUPYSONIC_RUN_MODE=fcgi-port \
  -p 5000:5000
  ogarcia/supysonic
```

**Comment by vincentDcmps** [comment]
thanks for new option but don't seem work on my side 
port seem listening  put nothing else when I do request on supysonic

**Comment by ogarcia** [comment]
You need to put an ingress in front that supports fcgi. See an example with nginx [here](https://kubernetes.github.io/ingress-nginx/user-guide/fcgi-services/).

**Comment by vincentDcmps** [comment]
thanks for your help

**Pull request closed without merging**
